kind = "web"
previewPath = "/"
title = "DuneX"
version = "1.0.0"
id = "artifacts/dunex"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 22837

[services.development]
run = "pnpm --filter @workspace/dunex run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/dunex", "run", "build" ]
publicDir = "artifacts/dunex/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "22837"
BASE_PATH = "/"
